--
-- PostgreSQL database dump
--

\restrict wWUPGUzIcPmkaOV15fhJgx2NXRpR2ijk5bIHDPFvqVQjfnMovg0AoZYTxe8ZfhX

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: kli; Type: TABLE; Schema: public; Owner: drawfig
--

CREATE TABLE public.kli (
    id integer NOT NULL,
    user_id integer NOT NULL,
    token character varying NOT NULL,
    exp bigint NOT NULL
);


ALTER TABLE public.kli OWNER TO drawfig;

--
-- Name: kli_id_seq; Type: SEQUENCE; Schema: public; Owner: drawfig
--

ALTER TABLE public.kli ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kli_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: session_tokens; Type: TABLE; Schema: public; Owner: drawfig
--

CREATE TABLE public.session_tokens (
    id integer NOT NULL,
    user_id integer NOT NULL,
    token character varying NOT NULL,
    exp bigint NOT NULL
);


ALTER TABLE public.session_tokens OWNER TO drawfig;

--
-- Name: session_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: drawfig
--

ALTER TABLE public.session_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.session_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: drawfig
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    username character varying NOT NULL,
    join_date bigint NOT NULL,
    salt character varying NOT NULL,
    hash character varying NOT NULL
);


ALTER TABLE public.users OWNER TO drawfig;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: drawfig
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kli kli_pk; Type: CONSTRAINT; Schema: public; Owner: drawfig
--

ALTER TABLE ONLY public.kli
    ADD CONSTRAINT kli_pk PRIMARY KEY (id);


--
-- Name: kli kli_unique; Type: CONSTRAINT; Schema: public; Owner: drawfig
--

ALTER TABLE ONLY public.kli
    ADD CONSTRAINT kli_unique UNIQUE (user_id);


--
-- Name: kli kli_unique_1; Type: CONSTRAINT; Schema: public; Owner: drawfig
--

ALTER TABLE ONLY public.kli
    ADD CONSTRAINT kli_unique_1 UNIQUE (user_id);


--
-- Name: session_tokens session_tokens_pk; Type: CONSTRAINT; Schema: public; Owner: drawfig
--

ALTER TABLE ONLY public.session_tokens
    ADD CONSTRAINT session_tokens_pk PRIMARY KEY (id);


--
-- Name: session_tokens session_tokens_unique; Type: CONSTRAINT; Schema: public; Owner: drawfig
--

ALTER TABLE ONLY public.session_tokens
    ADD CONSTRAINT session_tokens_unique UNIQUE (user_id);


--
-- Name: users users_pk; Type: CONSTRAINT; Schema: public; Owner: drawfig
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pk PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict wWUPGUzIcPmkaOV15fhJgx2NXRpR2ijk5bIHDPFvqVQjfnMovg0AoZYTxe8ZfhX

